version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: rhajaina-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: rhajaina
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rhajaina-network

  mongo-express:
    image: mongo-express:1.0
    container_name: rhajaina-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    networks:
      - rhajaina-network

  redis:
    image: redis:7.2-alpine
    container_name: rhajaina-redis
    restart: unless-stopped
    command: redis-server --requirepass redispassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rhajaina-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: rhajaina-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:redispassword
    ports:
      - "8082:8081"
    depends_on:
      - redis
    networks:
      - rhajaina-network

  qdrant:
    image: qdrant/qdrant:v1.7.3
    container_name: rhajaina-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rhajaina-network

  nats:
    image: nats:2.10-alpine
    container_name: rhajaina-nats
    restart: unless-stopped
    command: >
      --cluster_name NATS
      --cluster nats://0.0.0.0:6222
      --http_port 8222
      --port 4222
      --js
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - rhajaina-network

volumes:
  mongodb_data:
  redis_data:
  qdrant_data:

networks:
  rhajaina-network:
    driver: bridge
