development:
  qdrant:
    url: http://localhost:6333
    api_key: null
    timeout: 60000
  
  moleculer:
    adapter: "moleculer-db-adapter-mongo"
    url: "mongodb://localhost:27017/rhajaina_dev"
    options:
      useNewUrlParser: true
      useUnifiedTopology: true
  
  redis:
    host: localhost
    port: 6379
    db: 0
    password: null
    keyPrefix: "rhajaina:dev:"

test:
  qdrant:
    url: http://localhost:6333
    api_key: null
    timeout: 30000
  
  moleculer:
    adapter: "moleculer-db-adapter-mongo"
    url: "mongodb://localhost:27017/rhajaina_test"
    options:
      useNewUrlParser: true
      useUnifiedTopology: true
  
  redis:
    host: localhost
    port: 6379
    db: 1
    password: null
    keyPrefix: "rhajaina:test:"

production:
  qdrant:
    url: ${QDRANT_URL}
    api_key: ${QDRANT_API_KEY}
    timeout: 60000
  
  moleculer:
    adapter: "moleculer-db-adapter-mongo"
    url: ${MONGODB_URL}
    options:
      useNewUrlParser: true
      useUnifiedTopology: true
      ssl: true
  
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    db: 0
    password: ${REDIS_PASSWORD}
    keyPrefix: "rhajaina:prod:"
    tls: {}
